### ISSUE TITLE
Title check is not compatible with new title theme technique

### ISSUE THREAD

**Issue by NateWr** [Otto42/theme-check#10]
4.1 introduces a new [title-tag](https://make.wordpress.org/core/2014/10/29/title-tags-in-4-1/) theme feature. For backwards compatibility, the following is recommended:

```
if ( ! function_exists( '_wp_render_title_tag' ) ) :
function theme_slug_render_title() {
    echo '<title>' . wp_title( '|', false, 'right' ) . "</title>\n";
}
add_action( 'wp_head', 'theme_slug_render_title' );
endif;
```

This is throwing an error with the new title checks introduced in 9a6cbcbbfd8d00ea5ddbec8f088cbd2898ff2653.

```
REQUIRED: The <title> tags can only contain a call to wp_title(). Use the wp_title filter to modify the output
```

Using just wp_title() in the recommended code prints immediately, instead of returning for the echo statement. This can be worked around using ob_start(), or splitting into three separate statements, but this seems like a round-about way to pass the test. Should the check be updated to allow false for wp_title()'s second attribute?

**Comment by monolux** [comment]
@Otto42 Can you provide a link to the backwards compat example in the codex and blog post you mention please.?

I think I am having issues with this being the last error, all others pass.

https://github.com/WordPress/theme-check/issues/191

**Comment by monolux** [comment]
@Otto42 I found what it was! It was a, you will be laughing, `<title>` tag commented out in the HTML.
Once I deleted the commented `<title>` tag the check passed.
So this means the check scans for all instances of `<title>` regardless of if it is in a comment or not.
If you can still provide the links you mentioned I am interested to read that, thank you.
