### ISSUE TITLE
Consider changing from RECOMMENDED to INFO

### ISSUE THREAD

**Issue by limestreet** [Otto42/theme-check#100]
https://github.com/Otto42/theme-check/blob/542e2b520c94f5455cbf86f8d59d3bc6555aac1e/checks/i18n.php#L52

In my opinion this is info for author/reviewer/developer to check there is a variable or not. If is variable it's  issue and MUST be addressed.

**Comment by Otto42** [comment]
If that was more accurate, I would make it REQUIRED.

If it was INFO, then it could be suppressed with the option to suppress those, so since it needs to be checked, I don't want it being suppressed. Thus, RECOMMENDED.

**Comment by limestreet** [comment]
REQUIRED sounds better, but I'm curious about possible "false-positives" - there are any?
From reviewer's point of view if there are some "false-positives" it should be INFO if not should be REQUIRED :)

**Comment by Otto42** [comment]
Of course there are possible false positives. Theme Check is not perfect, and it never will be. Parsing any arbitrary code is not an exact science. :)
