### ISSUE TITLE
_n translation function checking for incorrect arguments

### ISSUE THREAD

**Issue by langan** [Otto42/theme-check#118]
Looking at the code the theme checker is checking for 3 params

in here https://github.com/Otto42/theme-check/blob/63c3d83fe8c769f2e425b8ef2686e5939833e965/checks/textdomain.php

```
'_n' => array('singular', 'plural', 'domain'),
```

But the codex has 4 params _n 

```
<?php _n( $single, $plural, $number, $domain ) ?>
```

https://codex.wordpress.org/Function_Reference/_n

**Comment by Otto42** [comment]
The way that particular checker code works causes it to ignore the $number parameter, because it's only looking for strings. Therefore, the code as written is correct.

**Comment by langan** [comment]
Hi @Otto42 I think the reason I was seeing the check error was because woocommerce uses an item in an array like this

```
_n( '%s download remaining', '%s downloads remaining', $download['downloads_remaining'], 'woocommerce' )
```

So the theme checker is picking up the 'downloads_remaining' in $download['downloads_remaining'] as a string perhaps?

**Comment by Otto42** [comment]
Yeah, that's probably a case it cannot account for at present. I'll look into improving that.

**Comment by riddbengkok** [comment]
sprintf( _n( '%s download remaining', '%s downloads remaining', $download['downloads_remaining'])

remove the last argument 'woocommerce', so you just give 3 argument , i try and it can pass the theme check

**Comment by riddbengkok** [comment]
https://github.com/WordPress/theme-check/blob/master/checks/textdomain.php

	3 argumentis 
 '_n' => array('singular', 'plural', 'domain'),
