### ISSUE TITLE
Duplicate checks for `get_bloginfo`

### ISSUE THREAD

**Issue by grappler** [Otto42/theme-check#120]
It seems like we have duplicated checks for `get_bloginfo`. In `suggested.php` it is only recommended and in `more_deprecated.php` it is required.

https://github.com/Otto42/theme-check/blob/master/checks/suggested.php
https://github.com/Otto42/theme-check/blob/master/checks/more_deprecated.php

The get_option checks are also duplicated in https://github.com/Otto42/theme-check/blob/master/checks/required.php

Could we possibly delete `suggested.php` and `required.php`?

**Comment by Otto42** [comment]
Good idea. Consolidate, simplify, eliminate redundant checks.
