### ISSUE TITLE
Why doesn't Theme Check Accepts my Tags?

### ISSUE THREAD

**Issue by ahmadawais** [Otto42/theme-check#154]
I am submitting a theme at ThemeForest. I'd like the theme tags to be custom. But TC plugin throws warnings my way. E.g. 
Every tag I add gets flagged. Why is that? 
E.g. `WARNING: Found wrong tag, remove booking from your style.css header.` Now booking is a tag why does it get flagged?

**Comment by grappler** [comment]
The list of tags in the style.css are meant for w.org. We are currently in the final phase of updating the new tags. https://github.com/Otto42/theme-check/pull/145

**Comment by Otto42** [comment]
Theme Check uses the w.org standards. Other directories may have other standards.

**Comment by ihemant360** [comment]
How to fix this !

**Comment by ahmadawais** [comment]
@ihemant360 
One should use [these tags only](https://make.wordpress.org/themes/handbook/review/required/theme-tags/) you can read more about [new tags here](https://make.wordpress.org/themes/2016/05/24/new-theme-tags-have-arrived/).
