### ISSUE TITLE
Line # For Customizer Setting without Santize Callback?

### ISSUE THREAD

**Issue by ahmadawais** [Otto42/theme-check#155]
Can Theme Check specify the line # for the following check?

`REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.`

I have tested all the `add_settings()` instances and there are callback functions with each one of them.

**Comment by ahmadawais** [comment]
@grappler and @Otto42  What do you think about this one?

**Comment by grappler** [comment]
Getting the line number did not seem so easy but I got a method working that returns the setting name.
Try replacing the customizer.php in theme check with this: https://gist.github.com/grappler/6b7ac6b1072233e252de90b1c2e6a5a5

**Comment by ahmadawais** [comment]
@grappler Perfect!
`REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed. Found vr_credits in the file vr_section_footer.php.`

Now it is pointing out the issue with the settings name and the file name. Handy!

But I am confused where is the issue :(

```php 
// Setting: Credits.
		$wp_customize->add_setting( 'vr_credits', array(
			'type'                 => 'theme_mod',
			'default'              => 'Copyright &copy; 2015 <a href="/">VacationRentals&trade;</a>',
			'transport'            => 'refresh', // refresh or postMessage
			'capability'           => 'edit_theme_options',
			'sanitize_callback'    => 'vr_sanitize_html'
		) );
```

While the `vr_sanitize_html` function looks like this

```php
/**
 * HTML sanitization callback example.
 *
 * - Sanitization: html
 * - Control: text, textarea
 *
 * Sanitization callback for 'html' type text inputs. This callback sanitizes `$html`
 * for HTML allowable in posts.
 *
 * NOTE: wp_filter_post_kses() can be passed directly as `$wp_customize->add_setting()`
 * 'sanitize_callback'. It is wrapped in a callback here merely for example purposes.
 *
 * @see wp_filter_post_kses() https://developer.wordpress.org/reference/functions/wp_filter_post_kses/
 *
 * @param string $html HTML to sanitize.
 * @return string Sanitized HTML.
 */
function vr_sanitize_html( $html ) {
	return wp_filter_post_kses( $html );
}
```

Let me know if you have any idea about this.

Moreover, it'd be great of you create a PR for this updated code.

**Comment by Otto42** [comment]
The check is not perfect. It doesn't understand PHP code, it's just using regular expressions to look for things.

In this case, your use of semi-colons in the strings is confusing it. It thinks the statement ends at the first semi-colon it finds.

If you move your default value to be in a variable just before the function call, then it will still work properly and not confuse theme-check.

**Comment by grappler** [comment]
The problem is related to https://github.com/Otto42/theme-check/issues/36

What is this Pull Request that you talk about? :P

I will have a look at it.

**Comment by Otto42** [comment]
BTW, see issue #36

**Comment by ahmadawais** [comment]
@grappler I am talking about your GIST. I updated the lingo. 
It can be a perfect PR, you should add it to the repo, or let me know and I can on your behalf. 

https://gist.github.com/ahmadawais/67928c5b191c9aca0d01619b4983e3dc

**Comment by grappler** [comment]
@ahmadawais Sorry, I was joking, it must have gotten have gone missing on it's way to Pakistan. :stuck_out_tongue:

**Comment by ahmadawais** [comment]
@grappler I didn't see the `:P` there. On mobile 🔢

**Comment by ahmadawais** [comment]
@Otto42 Thanks a lot for help. Saved the day again. 

```php
// Setting: Credits.
		// Defualt in variable to avoid Theme Check issue on semi colons
		$footer_default = 'Copyright &copy; 2015 <a href="/">VacationRentals&trade;</a>';
		$wp_customize->add_setting( 'vr_credits', array(
			'type'                 => 'theme_mod',
			'default'              => $footer_default,
			'transport'            => 'refresh', // refresh or postMessage
			'capability'           => 'edit_theme_options',
			'sanitize_callback'    => 'vr_sanitize_html'
		) );
```

Works fine.
