### ISSUE TITLE
Wrong INFO, include in array recognized as include file

### ISSUE THREAD

**Issue by lessthanweb** [Otto42/theme-check#158]
The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 477: 'include' => $post_ids,

`get_posts( array(
				'include' => $post_ids,`

**Comment by Otto42** [comment]
INFO checks are for informational purposes only, to aid reviewers. If it's wrong, then it can be ignored. They don't fail themes for it.
