### ISSUE TITLE
You are not allowed to hide the admin bar when wpadminbar is used.

### ISSUE THREAD

**Issue by emiluzelac** [Otto42/theme-check#164]
So `REQUIRED: You are not allowed to hide the admin bar.` will show if author is using `#wpadminbar` ID in the stylesheet. 

I don't think that this is needed. There are few scenarios where authors will need `#wpadminbar`, like wall-to-wall images with an absolute position, featured images with the same, etc.

https://github.com/Otto42/theme-check/issues/127

**Comment by Micemade** [comment]
If theme check doesn't allow usage of #wpadminbar in css, then some filter should be added in WP_Admin_Bar class to allow adding css classes.
Theme authors (like us) are not trying to hide admin bar, but fix it's absolute position in regards to theme layout.

**Comment by emiluzelac** [comment]
That's not hiding, therefore it's fine!

**Comment by Micemade** [comment]
:) I get your sarcasm. My reply was driven by  frustration. Ignore my "suggestion" please. Maybe the theme check should return something like "Not allowed usage of #wpadminbar in theme styles", or "Not allowed any modification of admin bar appearance". I was using #wpadminbar in style.css to fix positioning absolute top in mobile frontend ... Had to find other way around.

**Comment by emiluzelac** [comment]
No sarcasm intended 🙂As far as the suggestion just leave them right here
and someone will go over.
