### ISSUE TITLE
Style tags

### ISSUE THREAD

**Issue by zauan** [Otto42/theme-check#39]
Hi,

My theme uses a custom made pagebuilder. All elements have their own folder and it includes a style.css file for that specific element. The check shows a false positive on "Tags: is either empty or missing in style.css header." due to this.

From what i see in the check file, there is a loop made trough all the css files present in the theme. Can this be changed to only parse the style.css file found in the root directory of the theme?

Best regards,
Stefan

**Comment by Otto42** [comment]
Using the global $data variable like this works for the plugin, but not for other cases where the checks are used independently, without the rest of the plugin code. Checks must be self-contained and functional on a standalone basis.

**Comment by Otto42** [comment]
Additionally, core itself looks through subdirectories one-level deep for style.css files as well. Now, admittedly, it only looks one level deeper, but still, style.css files should not be so named anywhere in a theme except for the main file. You should use different naming, or issues might occur elsewhere in the future.
