### ISSUE TITLE
Title check

### ISSUE THREAD

**Issue by zauan** [Otto42/theme-check#40]
Hi,

My theme includes an xml export file. This export has tags like `<title>`.

The plugins shows a false positive because of this ( " The <title> tags can only contain a call to wp_title(). Use the wp_title filter to modify the output" ).

Can this check be limited only to PHP files ?

Best regards,
Stefan

**Comment by Otto42** [comment]
Theme-check is intended to be run on themes that are to be uploaded to the WordPress.org theme repository. Themes uploaded to such probably should not be including an XML export file in the first place, so I'm inclined to say wontfix on this one.

**Comment by zauan** [comment]
Hi,

If i provide a pull request for this would you consider adding it ? I think that it would be a good idea to limit this check only to PHP files for speed as well.

Best regards,
Stefan

**Comment by Otto42** [comment]
No, we need to check all the files. If a theme is including files that it should not be including, then that's something we would want to look at.
