### ISSUE TITLE
CDN's

### ISSUE THREAD

**Issue by emiluzelac** [Otto42/theme-check#45]
Can we please change the following from recommended to required?

`
RECOMMENDED: Found the URL of a CDN in the code: netdna.bootstrapcdn.com/font-awesome. You should not load CSS or Javascript resources from a CDN, please bundle them with the theme.
`

We don't accept unless this was added via theme options and turned off by default. So far we had none, but it's optional.

**Comment by Otto42** [comment]
Changing it to required would mean auto-failing any theme that had it in there. Meaning that it could not even be "optional" via theme options.

**Comment by emiluzelac** [comment]
Fair enough, sorry for super late respond.
