### ISSUE TITLE
checks/screenshot.php has inconsistent text

### ISSUE THREAD

**Issue by pixolin** [Otto42/theme-check#48]
I am working on the German translation of the Theme Check plugin and stumbled upon two text strings that seem illogical for me:

* Screenshot size should be 880x660, to account for HiDPI displays. *Any 4:3 image size is acceptable,* but 880x660 is preferred.
* Screenshot is wrong size! Detected: <strong>%1$sx%2$spx</strong>. * Maximum allowed size is 880x660px.*

If ANY size is acceptable, it doesn't make sense to have a warning about a "Maximum allowed size".

**Comment by Otto42** [comment]
Yes, this is still a minor point where the rules are somewhat unclear and undetermined. Any size that is 4:3 technically works, but we still want to keep the filesizes small for speed reasons. 

The next version will address this, probably by removing some of the checks.

**Comment by Otto42** [comment]
Size increased to 1200x900 now, as that's what the handbook states. Reference #59
