### ISSUE TITLE
main.php refers in text to Theme Reviewers Mailing List

### ISSUE THREAD

**Issue by pixolin** [Otto42/theme-check#49]
File main.php has an error message 
"If you have found a bug or would like to make a suggestion or contribution why not join the <a href="http://wordpress.org/extend/themes/contact/">theme-reviewers mailing list</a> or leave a post on the <a href="http://wordpress.org/tags/theme-check?forum_id=10">WordPress forums</a>.', 'theme-check' ); ?></p>"

I may have missed something but to my knowledge, the theme-reviewers mailing list has been closed?

**Comment by Otto42** [comment]
Yes, there's a few references there that need fixing.

**Comment by Otto42** [comment]
Changes made in 7086eb8b9f47e5d1f71787d8d9c5763e34ca4665
