### ISSUE TITLE
Wrong message Tags:is either empty or missing in style.css header.

### ISSUE THREAD

**Issue by tenman** [Otto42/theme-check#50]
Tested Raindrops theme 1.276

https://wordpress.org/themes/raindrops/

In this theme, error of tag will occur when the theme check

I'm checked it why saying wrong message.

style_tags.php

```
foreach( $css_files as $cssfile => $content ) {
			if ( basename( $cssfile ) === 'style.css' ) {
				$data = get_theme_data_from_contents( $content );			
				break;
			}		
		}
```

add break, fine for me.

when Tags is blank

theme check say 'Found wrong tag, remove <strong>%1$s</strong> from your style.css header.'

```
} elseif( !empty( $tag) ) {
```
change from else to elseif( empty check ).

I think better

Is this a plug-in bug?

**Comment by Otto42** [comment]
What is the Tags header that triggers this issue?

**Comment by tenman** [comment]
$css_files $keys below

 ["/*******/public_html/wp/wp-content/themes/raindrops/languages/css/en_US.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/css3.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/fonts.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/style.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/reset-fonts-grids.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/rtl.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/childs/boots/style.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/media.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/grids.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/editor-style.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/responsiveness.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/fallback.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/admin-options.css"]=>

	if ( basename( $cssfile ) === 'style.css' ) conditional match two style.css in my case.

  ["/*******/public_html/wp/wp-content/themes/raindrops/style.css"]=>
  ["/*******/public_html/wp/wp-content/themes/raindrops/childs/boots/style.css"]=>

	themes/raindrops/childs/boots/style.css is not exists

	then empty values overwrite all

  result all empty value.

	function check() is checked only $data[ 'Tags' ] then alert tags error occured

**Comment by Otto42** [comment]
The Tags header is not allowed to be empty or missing, and you should not have more than one style.css file, even if it's in subdirectories. This can cause problems in WordPress itself, because it can and will look in subdirectories to find the main stylesheet file.
