### ISSUE TITLE
Theme URI and Author URI

### ISSUE THREAD

**Issue by benlumia007** [Otto42/theme-check#56]
Theme URI and Author URI cannot be the same, which comes to.. 

users can bypass this if use a "/" at the end of a uri. 

theme uri: http://www.domainname.com
author uri: http://www.domainname.com/

**Comment by emiluzelac** [comment]
Yep, as I reported in: https://wordpress.slack.com/archives/themereview/p1428536051003175

**Comment by Otto42** [comment]
Seems a bit minor to me. But if you want to make a PR, I'll accept it.

Note that there is no current check to see if they're the same, that's one of the old hardcoded bits. Make a new check for it.

**Comment by carolinan** [comment]
Are there any links besides Theme URI with WordPress.org that we should disallow?

**Comment by Otto42** [comment]
You could add in the w.org domain as well, since it redirects.

**Comment by carolinan** [comment]
Actually perhaps this should be combined with links.php in one file.
