### ISSUE TITLE
Variable function names

### ISSUE THREAD

**Issue by justintadlock** [Otto42/theme-check#62]
On a theme I was reviewing recently, I noticed TC wasn't picking up variable functions.  Here's some code from the theme:

	$post_type = 'register_post_type';

	$post_type( 'post-type', $args );

And:

	$encode = 'base64_encode';

	$encode( $content );

**Comment by Otto42** [comment]
Picking up on the use of variable functions is rather memory intensive. Essentially, you need to tokenize the whole thing and run through all the tokens. Which we do for some cases, but for a theme it's kind of a pain. Also, there's valid uses of variable functions, just not very many of them.

Detecting any use of the string "base64_encode" is easier, but also worked around with something like "base".64."_encode" or similar. TC can't reliably detect everything.

**Comment by dovy** [comment]
Also in a class, to get around eval, I output a PHP class dynamically and use $class_name to reference that class. So while I am following rules, anything put in place to combat this issue would flag that.  :)

**Comment by ernilambar** [comment]
I sometime use variable like shown in the example by Justin. Also to instantiate Class object in some cases. Is it bad practice? Just curious.

**Comment by Otto42** [comment]
It is a bad practice, yes, for a lot of reasons. And if you do anything to "get around" theme-check, then we'll eventually find it and remove your themes from the repository for doing it. With prejudice.

Eval is banned for a reason. Doing anything to work around the automated checks is not allowed.

**Comment by szepeviktor** [comment]
Wouldn't a regexp be enough for finding variable function names?

`grep "\$[a-zA-Z0-9_]\+\s*("`

**Comment by Otto42** [comment]
Yeah, that doesn't work because people are to clever. Tokenizing works but it's slow. I'll look into it.

**Comment by szepeviktor** [comment]
OK.
I meant a simple regexp is much better than nothing.

**Comment by Otto42** [comment]
Relevant #87

Closing in favor of that. I have some ideas there.
