### ISSUE TITLE
WARNING: Found PHP short tags - Regex

### ISSUE THREAD

**Issue by dovy** [Otto42/theme-check#64]
WARNING: Found PHP short tags in file ~/parsedown.php.

See: https://github.com/erusev/parsedown/blob/master/Parsedown.php#L758

Any way to fix this?

**Comment by Otto42** [comment]
Yeah, that's a bit tricky.

You could modify the regex to have [<]? instead of just <?. Should have the same effect.

**Comment by dovy** [comment]
Good call, I'll make that change.
