### ISSUE TITLE
WARNING: file_put_contents/file_get_contents was found…

### ISSUE THREAD

**Issue by dovy** [Otto42/theme-check#67]
The full error also says curl_exec & curl_init were found, which is false.

Will this be a blocker? Let me explain. Redux uses these items are primarily fallback for when the WP_Filesystem fails. And oh yes, it does fail on odd hosts. We found that by doing this, we've reduced nearly 90% of permission error requests, and everything still works as expected.

We try the FileSystem API first, but then do this if it fails. Here's the code: https://github.com/reduxframework/redux-framework/blob/master/ReduxCore/inc/class.redux_filesystem.php#L160-L166

Any chance we can get "white-flagged" or find a way to allow this as a fallback?

**Comment by dovy** [comment]
Also makes me want to use #62.  :P

**Comment by Otto42** [comment]
Generally speaking, I would say no. file_put_contents is not a safe function to use on many hosting systems. This is a security issue.

**Comment by dovy** [comment]
Interesting... That's a little sad since we TRY to use the API properly, and this has actually all but removed all the issues.

Why do you say file_put_contents is a security issue? I'd just like to understand/

**Comment by Otto42** [comment]
On a shared hosting situation, Apache (and PHP) may be running as a shared account, like "nobody". Using file_put_contents will thus create a file owned by "nobody". And anybody else who has the ability to run code on that shared host can then see and modify that file's contents.

This is avoided by using SetUID methods for shared hosting, but not all hosts do that. WordPress's Filesystem API detects and avoids this situation. That's one of the reasons it exists.

**Comment by Otto42** [comment]
I grant you that this is not an issue on a properly setup shared web hosting environment. Assuming that a low-end cheap shared web hosting environment is properly setup, well... :) 

Most big well-known shared hosts don't have this problem. They use SetUID methods to ensure that the PHP process runs as the user and not as "nobody", and/or they have other security approaches to ensure that cross-user-account access is not permitted, regardless of file ownership and permissions and such.

**Comment by dovy** [comment]
I guess, in my eyes, this is similar to the php 5.2 issue. We shouldn't enable hosts to have bad practices. It's up to them to configure properly, not us to enable bad design. But alas, WP makes exceptions. ;)

**Comment by Otto42** [comment]
> We shouldn't enable hosts to have bad practices. 

We also shouldn't let bad practices cause security issues in our software.

**Comment by dovy** [comment]
How is a native php function bad practices? Hah.

**Comment by Otto42** [comment]
Programming languages let you shoot yourself in the foot all the time. Look at C and pointer logic. Just because the function is native does not make it safe to use in all circumstances. This is not a safe world we live in, friend.

**Comment by Otto42** [comment]
Also, note that in an environment where file_put_contents is safe, the WP_Filesystem API will indeed use it. The WP_Filesystem_Direct class actually uses fopen and fwrite, but it amounts to the same basic thing. So, there shouldn't be any case where you need to use it yourself. 

If you work out the specific cases where it's helping, then you'll probably find some deeper problem with that particular hosting environment that needs to be fixed.

**Comment by dovy** [comment]
Indeed. Heard of GoDaddy? haha.

**Comment by Otto42** [comment]
GoDaddy's hosting systems support the WP_Filesystem_Direct mode just fine. They run their PHP instances using a setUID method. Been there, used it.
