### ISSUE TITLE
Clean up checks

### ISSUE THREAD

**Issue by noplanman** [Otto42/theme-check#69]
I'm busy cleaning up the checks and noticed that the class names aren't prefixed, which could potentially break the theme if it has an own class with the same name. I know that theme check gets used mainly by the theme review team, but if a theme should have a class with the same name, the plugin can't be used.

Shall I prefix them all with `TC_` or something else?

**Comment by Otto42** [comment]
If a theme has a class with that same name, then it rightly should break. Themes are supposed to prefix their own classes and function names.

**Comment by noplanman** [comment]
Ok, I'll do nothing then.
