### ISSUE TITLE
Remove comment checks

### ISSUE THREAD

**Issue by karmatosed** [Otto42/theme-check#7]
We have removed the requirement for comments.php to be in themes. Do checks also need to be removed such as comment pagination and tags?

**Comment by Otto42** [comment]
I'd like to know cases where not having a comment.php makes sense, actually. Relying on the default provided by WordPress for backwards compatibility seems strange.

**Comment by Clorith** [comment]
When used as a CMS rather than a blog, it's not uncommon to disable comments sitewide, I'm guessing that's the use case in question here: sites not made for visitor input.

**Comment by noplanman** [comment]
I agree with @Clorith, most single page sites that have no blog element, don't offer commenting.

**Comment by Otto42** [comment]
That's as may be, however, theme-check is specifically intended to apply to themes listed in the official w.org repository. A theme listed there should support comments, in some fashion, because it is being offered to the public as a general-purpose theme.
