### ISSUE TITLE
Allow <title> element inside SVG elements

### ISSUE THREAD

**Issue by joedolson** [Otto42/theme-check#73]
The <title> element is an important accessibility feature for SVG images to provide accessible labels for those images. Current version of theme-check doesn't differentiate between a document <title> and an SVG <title>.

**Comment by Otto42** [comment]
What would these elements look like? How can I distinguish title's in svg's from title's not in svg's?

**Comment by joedolson** [comment]
I think the only way to distinguish them would be by context; if they're preceded by <svg>, it can't be occurring in the <head>, and therefore can't be the document title element. But that's kind of nasty. 

Because of browser support, the accessibility of inline SVG images is considerably better than the accessibility of external SVG images. Unfortunately, for this problem.

**Comment by Otto42** [comment]
So, look for anything that looks like `<svg>...</svg>` and exclude it for the purposes of this check. That enough to do the job?

**Comment by joedolson** [comment]
I think that's sufficient.
