### ISSUE TITLE
PHP Notice - undefined variable domain

### ISSUE THREAD

**Issue by ernilambar** [Otto42/theme-check#77]
Notice: Undefined variable: domain in /var/www/staging.dev/public_html/wp-content/plugins/theme-check/checks/textdomain.php on line 97

In line 97:
`$token = $found_domain? ')' : ", '$domain')";`

Checked theme: Twenty Fifteen
OS: Ubuntu 14.04

**Comment by Otto42** [comment]
That line was removed in https://github.com/Otto42/theme-check/commit/b4f7cda1604619baad93d5b930ceb64814ba6ed6
