### ISSUE TITLE
Updated deprecated list 4.0 - 4.3

### ISSUE THREAD

**Issue by justintadlock** [Otto42/theme-check#79]
Here's that list of updated deprecated functions.  Not sure if you need all because some aren't really applicable to themes.

## wp-includes:

	// 4.3
	wp_richedit_pre // Use format_for_editor()
	wp_htmledit_pre // Use format_for_editor()

	// 4.2
	// Use 'customize_dynamic_setting_args' filter instead of these:
	WP_Customize_Widgets::setup_widget_addition_previews()
	WP_Customize_Widgets::prepreview_added_sidebars_widgets()
	WP_Customize_Widgets::prepreview_added_widget_instance()
	WP_Customize_Widgets::remove_prepreview_filters() 

	// 4.1
	WP_Customize_Image_Control::prepare_control()
	WP_Customize_Image_Control::add_tab()
	WP_Customize_Image_Control::remove_tab()
	WP_Customize_Image_Control::print_tab_image()

	// 4.0
	get_all_category_ids()        // Use get_terms()
	like_escape()                 // Use wpdb::esc_like()
	url_is_accessable_via_ssl()
	FORCE_SSL_LOGIN               // constant - Use force_ssl_admin( true ) ??

## wp-admin

	// 4.3
	wp_ajax_wp_fullscreen_save_post()

**Comment by Otto42** [comment]
Sorry I forgot to notify you, I committed this about 6 hours ago. Check if I missed anything.

https://github.com/Otto42/theme-check/commit/e84d9414f447ad67705ad098f9adf2061deaff72

**Comment by justintadlock** [comment]
Looks good.
