### ISSUE TITLE
Same text domain displayed as different

### ISSUE THREAD

**Issue by ernilambar** [Otto42/theme-check#80]
When same text domain is used but apostrophe is different TC is displaying them as different. 
Example:
`
INFO: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are 'modality',"modality"
`

**Comment by santosh90** [comment]
INFO: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are twentyfifteen,tribute,twentythirteen,twentyeleven
![error](https://cloud.githubusercontent.com/assets/8736781/10512060/4da8e334-735b-11e5-926d-31e26d1a3838.png)

**Comment by Otto42** [comment]
@santosh90 Those are four different text domains. That is a correct error. Fix your text domains.
