### ISSUE TITLE
Possible bug in the language identifier constant area

### ISSUE THREAD

**Issue by Frumph** [Otto42/theme-check#83]
INFO: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are comicpress,comicpress

looked for comicpress,comicpress   
looked for comicpress,
looked for ,comicpress

couldn't find anything but 'comicpress'

**Comment by Otto42** [comment]
This is the problem in your theme:

`<div class="commentnav-left"><?php previous_comments_link(__( '&darr; Previous Comments', 'comicpress ')) ?></div>`

Note that your text domain has a space in it at the end. What that message is telling you is that you have two different text-domains, "comicpress", and "comicpress with a space at the end".

**Comment by Frumph** [comment]
single quotes around the entries maybe ?  heh did not think of space for some reason, thank you Otto!
