### ISSUE TITLE
title-tag support required

### ISSUE THREAD

**Issue by justintadlock** [Otto42/theme-check#84]
Now that WP 4.3 is out, `title-tag` should be a requirement rather than recommendation.  This is was decided in the latest TRT meeting: https://wordpress.slack.com/archives/themereview/p1440526841000503

I'll see about putting together a PR.

**Comment by Otto42** [comment]
Not criticizing, but WordPress 4.1 was released 9 months ago, on December 18, 2014. That's a bit short on the back-compat scale. Perhaps it might be worth extending that to a flat year, if we're doing three releases a year? Something to discuss among the TRT.

**Comment by justintadlock** [comment]
Definitely. It's something we've discussed once but didn't come to an agreement.  I'd rather start getting us to shoot for 3-4 releases.

**Comment by Otto42** [comment]
Given the proposed release date for 4.4, this would be appropriate now if somebody wants to make a patch.

**Comment by limestreet** [comment]
Do you mean guys changing "recommended" to "required" in two places in this line??
https://github.com/Otto42/theme-check/blob/5a14a62ae7c4e6f8a559a2fb03db8512e70d874c/checks/title.php#L20

**Comment by justintadlock** [comment]
That'd be the biggest thing.  `wp_title()` should also no longer be a requirement.

We might need to consider checking that themes are not using `wp_title()`  at all.  Should definitely be discouraged.

Maybe a check for `<title>`/`</title>` too??  I can't think of any legit use cases for this off the top of my head, but we might not need a check for it.

**Comment by Otto42** [comment]
A `<title>/</title>` check might be tricky. SVG files can have titles too.

**Comment by limestreet** [comment]
As I understand add_theme_support( "title-tag" ) will be required soon and there is no reason in themes to use <title>/</title> and wp_title(). Then not using them should be required.

So these checks look good:

		// Look for add_theme_support( 'title-tag' ) first
                checkcount();
		if ( ! preg_match( '#add_theme_support\s?\(\s?[\'|"]title-tag#', $php ) ) {
			$this->error[] = '<span class="tc-lead tc-required">'.__('REQUIRED','theme-check').'</span>: '.__('No reference to <strong>add_theme_support( "title-tag" )</strong> was found in the theme. It is recommended that the theme implement this functionality for WordPress 4.1 and above.', 'theme-check' );
			$ret = false;
		}
		
		// Check whether there is a call to wp_title()
		checkcount();
		if ( true === strpos( $php, 'wp_title(' ) ) {
			$this->error[] = '<span class="tc-lead tc-required">' . __( 'REQUIRED', 'theme-check').'</span>: ' . __( 'The theme must not use <strong>wp_title()</strong>, please use <strong>add_theme_support( "title-tag" )</strong> instead.', 'theme-check' );
			$ret = false;
		} 

But for `<title>/</title>` check - I see 2 solutions:

1. Output INFO for:

		`// Look for <title> and </title> tags.
		checkcount();
		if ( ( true === strpos( $php, '<title>' ) || true === strpos( $php, '</title>' ) ) ) {
			$this->error[] = '<span class="tc-lead tc-info">' . __( 'INFO', 'theme-check').'</span>: ' . __( 'The theme must not have <strong>&lt;title&gt;</strong> tags.', 'theme-check' );
			$ret = false;
		}`
		
2. or use this part as REQUIRED:

			`foreach ( $php_files as $file_path => $file_content ) {
			// Look for anything that looks like <svg>...</svg> and exclude it (inline svg's have titles too)
			$file_content = preg_replace('/<svg>.*<\/svg>/s', '', $file_content);
			
			// First looks ahead to see of there's <title>...</title>
			// Then performs a negative look ahead for <title> wp_title(...); </title>
			if ( preg_match( '/<title>(.*)<\/title>/', $file_content ) ) {
				$this->error[] = '<span class="tc-lead tc-required">' . __( 'REQUIRED', 'theme-check').'</span>: ' . __( 'The theme must not have <strong>&lt;title&gt;</strong> tags', 'theme-check' );
				$ret = false;
			}
		}`
		
What do you think guys?

**Comment by Otto42** [comment]
The wp_title function isn't actually getting deprecated anymore, because there are lots of other cases where it's being used for other things. So we can't require it to be missing from the theme.

I think this whole file probably just need a rewrite, to consider the various current cases. Some of it applies, some of it probably does not. I'll rewrite it sometime before 4.4.

**Comment by grappler** [comment]
What about just a warning when `wp_title()` is used in the header.php? This will helps those who use the theme check plugin to pick up on this.

**Comment by Otto42** [comment]
#148
