### ISSUE TITLE
Favicons/icons check

### ISSUE THREAD

**Issue by justintadlock** [Otto42/theme-check#85]
With the new favicon feature in WP 4.3, we need to add an info notice if we spot favicons.  I haven't completely looked into what all core does, but I believe it adds other icons as well.  Not sure right off the top of my head what this check needs to look like.

Themes should only add this feature if < 4.3, so it should be an info notice.

**Comment by Otto42** [comment]
That's a tricky one to detect. Could be simplistic about it and just look for the string "favicon" anywhere, as long as it's only an INFO.

Some examples of themes with this feature would be useful to analyse and look for some form of commonality.

**Comment by justintadlock** [comment]
That's what I was thinking -- it'd be tricky.  I've seen a couple of themes recently that had multiple icons.  I'll look and see what strings we could use.

**Comment by justintadlock** [comment]
These are the tags from core:

	$meta_tags = array(
		sprintf( '<link rel="icon" href="%s" sizes="32x32" />', esc_url( get_site_icon_url( 32 ) ) ),
		sprintf( '<link rel="icon" href="%s" sizes="192x192" />', esc_url( get_site_icon_url( 192 ) ) ),
		sprintf( '<link rel="apple-touch-icon-precomposed" href="%s">', esc_url( get_site_icon_url( 180 ) ) ),
		sprintf( '<meta name="msapplication-TileImage" content="%s">', esc_url( get_site_icon_url( 270 ) ) ),
	);

Rough draft for checks:

	'/<link rel=[\'"]icon[\'"]/'

	'/<link rel=[\'"]apple-touch-icon-precomposed[\'"]/'

	'/<meta name=[\'"]msapplication-TileImage[\'"]/'
