### ISSUE TITLE
register_sidebar issue

### ISSUE THREAD

**Issue by kprovance** [Otto42/theme-check#88]
Per this:  REQUIRED: Sidebars need to be registered in a custom function hooked to the widgets_init action. See: register_sidebar().

Well, my widget_init, which handles the register_sidebar is inside a class, the action hook set in the constructor.  theme-check doesn't see this.  Maybe it should.  Some of us prefer to use classes vs. loose functions and would prefer to not have to explain to themeforest a million times over the function is actually there and valid, but theme check just refuses to see it.

**Comment by Otto42** [comment]
Can you provide example code that should pass but fails?

**Comment by kprovance** [comment]
Yup

```php
If (!class_exists('myClass)) {
    class myClass {
        public function __construct () {
            add_action ( 'widgets_init', array($this, 'sidebars_init' ));
        }

        public function sidebars_init() {
            register_sidebar ( array(
                'name'          => __ ( 'My Sidebar', 'mytheme' ),
                'id'            => 'main-sidebar',
                'before_widget' => '<div id="%1$s" class="widget %2$s">',
                'after_widget'  => '</div>',
                'before_title'  => '<h3 class="widget-title"><span>',
                'after_title'   => '</span></h3>',
            ) );

            // more register_sidebars calls.              
        }
    }
}
```
Theme check does not see it, TF barks.  Everyone is sad.  World ends.  Profit.  Repeat.

Cheers.

**Comment by Otto42** [comment]
Okay, I'll take a look at the checks. That should pass, I feel.

**Comment by Otto42** [comment]
Actually, looking at the widgets.php check, that should pass fine. It should see the add action without caring what it is hooked to.

**Comment by Otto42** [comment]
Found it. The space between the add_action and the opening parentheses is the problem. I'll make that check a bit more tolerant.

**Comment by kprovance** [comment]
Oh yeah,, the formatting.  Always spaces, everyone.  Habit from the Visual Studio days.

**Comment by Otto42** [comment]
No worries. Theme check isn't perfect. There's more than a few of these that need to be adjusted. I'll try to get to it this week.

**Comment by Codevz** [comment]
I have same problem. My `widgets_init` is inside class and theme check showing that error.

**Comment by pranonTeam** [comment]
I have faced same problem. when i used class and their method to initialize widgets_init then theme-check shows error. :(
