### ISSUE TITLE
Detect @import and also CDN URL

### ISSUE THREAD

**Issue by ernilambar** [Otto42/theme-check#90]
While I was reviewing a theme I found following in `style.css`.

Detect CDN import in style.css.

`@import url(//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css);`

This should be blocker I believe.

Also, may be it would be good to detect `@import` and recommend theme author to use proper hooks and functions to load styles and fonts.

`@import url(http://fonts.googleapis.com/css?family=Arimo:400,400italic,700,700italic);`

**Comment by Otto42** [comment]
The cdn.php check only checks the php code, not the CSS files. It should check both.
