### ISSUE TITLE
Figuring out a text-domain error

### ISSUE THREAD

**Issue by gareth-gillman** [Otto42/theme-check#93]
In a theme check result I get the following:

The domains found are theme,,,cmb2,tgmpa

The issue is the 3 commas inbetween theme and cmb2, I know it means I probably have made a mistake in the text-domain in one of my files, but I have triple checked all my files and can't find a ,, (2 commas) in any of the files, is there a specific format of the text-domain which would cause this to happen?

**Comment by Otto42** [comment]
No, it likely found blank or empty domain names.
