### ISSUE TITLE
how do i run the check after plugin is installed?

### ISSUE THREAD

**Issue by rothschild86** [Otto42/theme-check#94]
For the life of me, cannot find where it is...

(good FAQ candidate?)

**Comment by grappler** [comment]
You find the page under Appearance.
![image](https://cloud.githubusercontent.com/assets/1785641/10123182/088a6664-6533-11e5-9ce2-dd6a9a9c8b1e.png)

**Comment by rothschild86** [comment]
Thx :) Def a FAQ candidate :)
