### ISSUE TITLE
File input!

### ISSUE THREAD

**Issue by szepeviktor** [Otto42/theme-check#97]
Please consider checking for `<input type="file" />` which is not the nicest thing.
Seen [here](http://themeforest.net/item/seed-organic-shop-farm-food-coffee-cosmetic-bio/11809011).

**Comment by Otto42** [comment]
Why is a file input bad, exactly? I get that they should use a proper upload handler, but would need some good reason to blanket kill it.

**Comment by szepeviktor** [comment]
I think not using WP Media is the start of an avalanche. It should be at least a warning.
No template author will implement sanitazation, file placement, handling etc.

**Comment by Otto42** [comment]
Even using the proper WP media handling functions, there are cases where you would make your own input type=file box, for custom styling. Cases I can think of where you'd do this sort of thing in a custom control for the Customizer. 

The thing that would be bad here would be improperly handling the uploaded media file by not calling the WP upload handler function to deal with the resulting file.

**Comment by Otto42** [comment]
Wontfix for now, but if a suitable case occurs where this makes sense, then we'll consider it for that case.

**Comment by szepeviktor** [comment]
OK
