### ISSUE TITLE
Child theme: Problem with text domain check 

### ISSUE THREAD

**Issue by FlorianBrinkmann** [Otto42/theme-check#98]
Hey!

If I test a child theme with the plugin I get the message:

> Your theme appears to be in the wrong directory for the theme name. The directory name must match the slug of the theme. This theme's correct slug and text-domain is theme-child.

The parent theme is named “Theme” and the child theme “Theme Child”. The directory of the child theme is named “theme-child” as well as the `Text Domain:` in the `style.css`. So I tried to output `$themename` and `$correct_domain` from the `textdomain.php` and I get ”theme“ for the `$themename` and ”theme-child” for `$correct_domain`. Is it possible that the plugin uses the name of the parent theme at this point?

**Comment by Otto42** [comment]
Child theme support is very bad and likely broken in many ways. Fixes are welcome though, if you can find the problem.

**Comment by Otto42** [comment]
Partial fix for this in https://github.com/Otto42/theme-check/commit/63c3d83fe8c769f2e425b8ef2686e5939833e965
